# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='comment',
        ),
        migrations.AddField(
            model_name='commentproblem',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.Problems'),
        ),
    ]
