# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20170515_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproblem',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='Project.Problems'),
        ),
    ]
