# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20170515_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='Project.Projects'),
        ),
    ]
