# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_problems_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='p',
        ),
    ]
